### ISSUE TITLE
Unable to lock database: Permission denied

### ISSUE THREAD

**Issue by bgualda** [felixhummel/docker-plantuml-server#1]
Hi guys !

I have problems to build from docker-compose, see:

Building app
Step 1/4 : FROM jetty:alpine
 ---> 71b82b5685db
Step 2/4 : RUN apk add --no-cache graphviz fontconfig ttf-dejavu
 ---> Running in 3ec3a36a3c2d
ERROR: Unable to lock database: Permission denied
ERROR: Failed to open apk database: Permission denied
ERROR: Service 'app' failed to build: The command '/bin/sh -c apk add --no-cache graphviz fontconfig ttf-dejavu' returned a non-zero code: 243

**Comment by felixhummel** [comment]
Upstream `jetty:alpine` seems to have switched to an unprivileged user.
It's best practice anyways
```
$ docker run -it --rm jetty:alpine sh -c 'pwd; id'
/var/lib/jetty
uid=100(jetty) gid=101(jetty) groups=101(jetty)
```

**Comment by bgualda** [comment]
OK, thanks
